// Code generated by "stringer -type=ItemType"; DO NOT EDIT.

package item

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownItemType-0]
	_ = x[EmptySlot-1]
	_ = x[Bulk-2]
	_ = x[Gear-3]
	_ = x[Trinket-4]
	_ = x[Tool-5]
	_ = x[Armor-6]
	_ = x[Weapon-7]
	_ = x[SpellBook-8]
	_ = x[Relic-9]
}

const _ItemType_name = "UnknownItemTypeEmptySlotBulkGearTrinketToolArmorWeaponSpellBookRelic"

var _ItemType_index = [...]uint8{0, 15, 24, 28, 32, 39, 43, 48, 54, 63, 68}

func (i ItemType) String() string {
	if i < 0 || i >= ItemType(len(_ItemType_index)-1) {
		return "ItemType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ItemType_name[_ItemType_index[i]:_ItemType_index[i+1]]
}
