// Code generated by "stringer -type=StatusType"; DO NOT EDIT.

package status

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HP-0]
	_ = x[MaxHP-1]
	_ = x[Str-2]
	_ = x[MaxStr-3]
	_ = x[Dex-4]
	_ = x[MaxDex-5]
	_ = x[Will-6]
	_ = x[MaxWill-7]
}

const _StatusType_name = "HPMaxHPStrMaxStrDexMaxDexWillMaxWill"

var _StatusType_index = [...]uint8{0, 2, 7, 10, 16, 19, 25, 29, 36}

func (i StatusType) String() string {
	if i < 0 || i >= StatusType(len(_StatusType_index)-1) {
		return "StatusType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StatusType_name[_StatusType_index[i]:_StatusType_index[i+1]]
}
