// Code generated by "stringer -type=Gender"; DO NOT EDIT.

package gender

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Undefined-0]
	_ = x[Intersex-1]
	_ = x[Indeterminate-2]
	_ = x[Fluid-3]
	_ = x[Female-4]
	_ = x[Male-5]
}

const _Gender_name = "UndefinedIntersexIndeterminateFluidFemaleMale"

var _Gender_index = [...]uint8{0, 9, 17, 30, 35, 41, 45}

func (i Gender) String() string {
	if i < 0 || i >= Gender(len(_Gender_index)-1) {
		return "Gender(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Gender_name[_Gender_index[i]:_Gender_index[i+1]]
}
