// Code generated by "stringer -type=Clothing -trimprefix Clothing"; DO NOT EDIT.

package trait

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ClothingAntique-0]
	_ = x[ClothingBloody-1]
	_ = x[ClothingElegant-2]
	_ = x[ClothingFilthy-3]
	_ = x[ClothingForeign-4]
	_ = x[ClothingFrayed-5]
	_ = x[ClothingFrumpy-6]
	_ = x[ClothingLivery-7]
	_ = x[ClothingRancid-8]
	_ = x[ClothingSoiled-9]
}

const _Clothing_name = "AntiqueBloodyElegantFilthyForeignFrayedFrumpyLiveryRancidSoiled"

var _Clothing_index = [...]uint8{0, 7, 13, 20, 26, 33, 39, 45, 51, 57, 63}

func (i Clothing) String() string {
	if i < 0 || i >= Clothing(len(_Clothing_index)-1) {
		return "Clothing(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Clothing_name[_Clothing_index[i]:_Clothing_index[i+1]]
}
