// Code generated by "stringer -type=Face -trimprefix Face"; DO NOT EDIT.

package trait

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FaceBony-0]
	_ = x[FaceBroken-1]
	_ = x[FaceChiseled-2]
	_ = x[FaceElongated-3]
	_ = x[FacePale-4]
	_ = x[FacePerfect-5]
	_ = x[FaceRatlike-6]
	_ = x[FaceSharp-7]
	_ = x[FaceSquare-8]
	_ = x[FaceSunken-9]
}

const _Face_name = "BonyBrokenChiseledElongatedPalePerfectRatlikeSharpSquareSunken"

var _Face_index = [...]uint8{0, 4, 10, 18, 27, 31, 38, 45, 50, 56, 62}

func (i Face) String() string {
	if i < 0 || i >= Face(len(_Face_index)-1) {
		return "Face(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Face_name[_Face_index[i]:_Face_index[i+1]]
}
