// Code generated by "stringer -type=Misfortune -trimprefix Misfortune"; DO NOT EDIT.

package trait

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MisfortuneAbandoned-0]
	_ = x[MisfortuneAddicted-1]
	_ = x[MisfortuneBlackmailed-2]
	_ = x[MisfortuneCondemed-3]
	_ = x[MisfortuneCursed-4]
	_ = x[MisfortuneDefrauded-5]
	_ = x[MisfortuneDemoted-6]
	_ = x[MisfortuneDiscredited-7]
	_ = x[MisfortuneDisowned-8]
	_ = x[MisfortuneExiled-9]
}

const _Misfortune_name = "AbandonedAddictedBlackmailedCondemedCursedDefraudedDemotedDiscreditedDisownedExiled"

var _Misfortune_index = [...]uint8{0, 9, 17, 28, 36, 42, 51, 58, 69, 77, 83}

func (i Misfortune) String() string {
	if i < 0 || i >= Misfortune(len(_Misfortune_index)-1) {
		return "Misfortune(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Misfortune_name[_Misfortune_index[i]:_Misfortune_index[i+1]]
}
