// Code generated by "stringer -type=Reputation -trimprefix Reputation"; DO NOT EDIT.

package trait

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ReputationAbitious-0]
	_ = x[ReputationBoor-1]
	_ = x[ReputationDangerous-2]
	_ = x[ReputationEntertainer-3]
	_ = x[ReputationHonest-4]
	_ = x[ReputationLoafer-5]
	_ = x[ReputationOddball-6]
	_ = x[ReputationRepulsive-7]
	_ = x[ReputationRespected-8]
	_ = x[ReputationWise-9]
}

const _Reputation_name = "AbitiousBoorDangerousEntertainerHonestLoaferOddballRepulsiveRespectedWise"

var _Reputation_index = [...]uint8{0, 8, 12, 21, 32, 38, 44, 51, 60, 69, 73}

func (i Reputation) String() string {
	if i < 0 || i >= Reputation(len(_Reputation_index)-1) {
		return "Reputation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Reputation_name[_Reputation_index[i]:_Reputation_index[i+1]]
}
