// Code generated by "stringer -type=Skin -trimprefix Skin"; DO NOT EDIT.

package trait

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SkinBirthmark-0]
	_ = x[SkinDark-1]
	_ = x[SkinElongated-2]
	_ = x[SkinPockmarked-3]
	_ = x[SkinRosy-4]
	_ = x[SkinRound-5]
	_ = x[SkinSoft-6]
	_ = x[SkinTanned-7]
	_ = x[SkinTattooed-8]
	_ = x[SkinWeathered-9]
}

const _Skin_name = "BirthmarkDarkElongatedPockmarkedRosyRoundSoftTannedTattooedWeathered"

var _Skin_index = [...]uint8{0, 9, 13, 22, 32, 36, 41, 45, 51, 59, 68}

func (i Skin) String() string {
	if i < 0 || i >= Skin(len(_Skin_index)-1) {
		return "Skin(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Skin_name[_Skin_index[i]:_Skin_index[i+1]]
}
