// Code generated by "stringer -type=Speech -trimprefix Speech"; DO NOT EDIT.

package trait

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SpeechBlunt-0]
	_ = x[SpeechBooming-1]
	_ = x[SpeechCryptic-2]
	_ = x[SpeechDroning-3]
	_ = x[SpeechFormal-4]
	_ = x[SpeechGravelly-5]
	_ = x[SpeechPrecise-6]
	_ = x[SpeechSqueaky-7]
	_ = x[SpeechStuttering-8]
	_ = x[SpeechWhispery-9]
}

const _Speech_name = "BluntBoomingCrypticDroningFormalGravellyPreciseSqueakyStutteringWhispery"

var _Speech_index = [...]uint8{0, 5, 12, 19, 26, 32, 40, 47, 54, 64, 72}

func (i Speech) String() string {
	if i < 0 || i >= Speech(len(_Speech_index)-1) {
		return "Speech(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Speech_name[_Speech_index[i]:_Speech_index[i+1]]
}
