// Code generated by "stringer -type=Vice -trimprefix Vice"; DO NOT EDIT.

package trait

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ViceAggressive-0]
	_ = x[ViceBitter-1]
	_ = x[ViceCraven-2]
	_ = x[ViceDeceitful-3]
	_ = x[ViceGreedy-4]
	_ = x[ViceLazy-5]
	_ = x[ViceNervous-6]
	_ = x[ViceRude-7]
	_ = x[ViceVain-8]
	_ = x[ViceVengeful-9]
}

const _Vice_name = "AggressiveBitterCravenDeceitfulGreedyLazyNervousRudeVainVengeful"

var _Vice_index = [...]uint8{0, 10, 16, 22, 31, 37, 41, 48, 52, 56, 64}

func (i Vice) String() string {
	if i < 0 || i >= Vice(len(_Vice_index)-1) {
		return "Vice(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Vice_name[_Vice_index[i]:_Vice_index[i+1]]
}
