// Code generated by "stringer -type=Virtue -trimprefix Virtue"; DO NOT EDIT.

package trait

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VirtueAmbitious-0]
	_ = x[VirtueCautious-1]
	_ = x[VirtueCourageous-2]
	_ = x[VirtueDiciplined-3]
	_ = x[VirtueGregarious-4]
	_ = x[VirtueHonorable-5]
	_ = x[VirtueHumble-6]
	_ = x[VirtueMerciful-7]
	_ = x[VirtueSerene-8]
	_ = x[VirtueTollerant-9]
}

const _Virtue_name = "AmbitiousCautiousCourageousDiciplinedGregariousHonorableHumbleMercifulSereneTollerant"

var _Virtue_index = [...]uint8{0, 9, 17, 27, 37, 47, 56, 62, 70, 76, 85}

func (i Virtue) String() string {
	if i < 0 || i >= Virtue(len(_Virtue_index)-1) {
		return "Virtue(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Virtue_name[_Virtue_index[i]:_Virtue_index[i+1]]
}
