// Code generated by "stringer -type=TraitType"; DO NOT EDIT.

package trait

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Physique-0]
	_ = x[Skin-1]
	_ = x[Hair-2]
	_ = x[Face-3]
	_ = x[Speech-4]
	_ = x[Clothing-5]
	_ = x[Virtue-6]
	_ = x[Vice-7]
	_ = x[Reputation-8]
	_ = x[Misfortune-9]
}

const _TraitType_name = "PhysiqueSkinHairFaceSpeechClothingVirtueViceReputationMisfortune"

var _TraitType_index = [...]uint8{0, 8, 12, 16, 20, 26, 34, 40, 44, 54, 64}

func (i TraitType) String() string {
	if i < 0 || i >= TraitType(len(_TraitType_index)-1) {
		return "TraitType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TraitType_name[_TraitType_index[i]:_TraitType_index[i+1]]
}
