// Code generated by "stringer -type=AsexName"; DO NOT EDIT.

package name

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Wenlan-0]
}

const _AsexName_name = "Wenlan"

var _AsexName_index = [...]uint8{0, 6}

func (i AsexName) String() string {
	if i < 0 || i >= AsexName(len(_AsexName_index)-1) {
		return "AsexName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AsexName_name[_AsexName_index[i]:_AsexName_index[i+1]]
}
