// Code generated by "stringer -type=FemaleName -trimprefix Female"; DO NOT EDIT.

package name

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FemaleAgune-0]
	_ = x[FemaleBeatrice-1]
	_ = x[FemaleBreagan-2]
	_ = x[FemaleBronwyn-3]
	_ = x[FemaleCannora-4]
	_ = x[FemaleDrelil-5]
	_ = x[FemaleElgile-6]
	_ = x[FemaleEsme-7]
	_ = x[FemaleGroua-8]
	_ = x[FemaleHenaine-9]
	_ = x[FemaleLiranne-10]
	_ = x[FemaleLirathil-11]
	_ = x[FemaleLisabeth-12]
	_ = x[FemaleMoralil-13]
	_ = x[FemaleMorgwin-14]
	_ = x[FemaleSybil-15]
	_ = x[FemaleTheune-16]
	_ = x[FemaleYgwal-17]
	_ = x[FemaleYslen-18]
}

const _FemaleName_name = "AguneBeatriceBreaganBronwynCannoraDrelilElgileEsmeGrouaHenaineLiranneLirathilLisabethMoralilMorgwinSybilTheuneYgwalYslen"

var _FemaleName_index = [...]uint8{0, 5, 13, 20, 27, 34, 40, 46, 50, 55, 62, 69, 77, 85, 92, 99, 104, 110, 115, 120}

func (i FemaleName) String() string {
	if i < 0 || i >= FemaleName(len(_FemaleName_index)-1) {
		return "FemaleName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FemaleName_name[_FemaleName_index[i]:_FemaleName_index[i+1]]
}
