// Code generated by "stringer -type=MaleName -trimprefix Male"; DO NOT EDIT.

package name

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MaleArwel-0]
	_ = x[MaleBevan-1]
	_ = x[MaleBoroth-2]
	_ = x[MaleBorrid-3]
	_ = x[MaleBreagle-4]
	_ = x[MaleBreglor-5]
	_ = x[MaleCanhoreal-6]
	_ = x[MaleEmrys-7]
	_ = x[MaleEthex-8]
	_ = x[MaleGringle-9]
	_ = x[MaleGrinwit-10]
	_ = x[MaleGruwid-11]
	_ = x[MaleGruwth-12]
	_ = x[MaleGwestin-13]
	_ = x[MaleMannog-14]
	_ = x[MaleMelnax-15]
	_ = x[MaleOrthax-16]
	_ = x[MaleTriunein-17]
	_ = x[MaleYirmeor-18]
}

const _MaleName_name = "ArwelBevanBorothBorridBreagleBreglorCanhorealEmrysEthexGringleGrinwitGruwidGruwthGwestinMannogMelnaxOrthaxTriuneinYirmeor"

var _MaleName_index = [...]uint8{0, 5, 10, 16, 22, 29, 36, 45, 50, 55, 62, 69, 75, 81, 88, 94, 100, 106, 114, 121}

func (i MaleName) String() string {
	if i < 0 || i >= MaleName(len(_MaleName_index)-1) {
		return "MaleName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MaleName_name[_MaleName_index[i]:_MaleName_index[i+1]]
}
