// Code generated by "stringer -type=Surname -trimprefix Surname"; DO NOT EDIT.

package name

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SurnameAbernathy-0]
	_ = x[SurnameAddercap-1]
	_ = x[SurnameBurl-2]
	_ = x[SurnameCandlewick-3]
	_ = x[SurnameCormick-4]
	_ = x[SurnameCrumwaller-5]
	_ = x[SurnameDunswallow-6]
	_ = x[SurnameGetri-7]
	_ = x[SurnameGlass-8]
	_ = x[SurnameHarkness-9]
	_ = x[SurnameHarper-10]
	_ = x[SurnameLoomer-11]
	_ = x[SurnameMalksmilk-12]
	_ = x[SurnameSmythe-13]
	_ = x[SurnameSunderman-14]
	_ = x[SurnameSwinney-15]
	_ = x[SurnameThatcher-16]
	_ = x[SurnameTolmen-17]
	_ = x[SurnameWeaver-18]
	_ = x[SurnameWolder-19]
}

const _Surname_name = "AbernathyAddercapBurlCandlewickCormickCrumwallerDunswallowGetriGlassHarknessHarperLoomerMalksmilkSmytheSundermanSwinneyThatcherTolmenWeaverWolder"

var _Surname_index = [...]uint8{0, 9, 17, 21, 31, 38, 48, 58, 63, 68, 76, 82, 88, 97, 103, 112, 119, 127, 133, 139, 145}

func (i Surname) String() string {
	if i < 0 || i >= Surname(len(_Surname_index)-1) {
		return "Surname(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Surname_name[_Surname_index[i]:_Surname_index[i+1]]
}
