// Code generated by "stringer -type=Background"; DO NOT EDIT.

package background

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Alchemist-0]
	_ = x[Blacksmith-1]
	_ = x[Butcher-2]
	_ = x[Burglar-3]
	_ = x[Carpenter-4]
	_ = x[Cleric-5]
	_ = x[Gambler-6]
	_ = x[Gravedigger-7]
	_ = x[Herbalist-8]
	_ = x[Hunter-9]
	_ = x[Magician-10]
	_ = x[Mercenary-11]
	_ = x[Merchant-12]
	_ = x[Miner-13]
	_ = x[Outlaw-14]
	_ = x[Performer-15]
	_ = x[Pickpocket-16]
	_ = x[Smuggler-17]
	_ = x[Servant-18]
	_ = x[Ranger-19]
}

const _Background_name = "AlchemistBlacksmithButcherBurglarCarpenterClericGamblerGravediggerHerbalistHunterMagicianMercenaryMerchantMinerOutlawPerformerPickpocketSmugglerServantRanger"

var _Background_index = [...]uint8{0, 9, 19, 26, 33, 42, 48, 55, 66, 75, 81, 89, 98, 106, 111, 117, 126, 136, 144, 151, 157}

func (i Background) String() string {
	if i < 0 || i >= Background(len(_Background_index)-1) {
		return "Background(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Background_name[_Background_index[i]:_Background_index[i+1]]
}
