// Code generated by "stringer -type=Gear -linecomment"; DO NOT EDIT.

package item

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AirBladder-0]
	_ = x[Antitoxin-1]
	_ = x[Cart-2]
	_ = x[Chain-3]
	_ = x[DowsingRod-4]
	_ = x[FireOil-5]
	_ = x[GrapplingHook-6]
	_ = x[LargeSack-7]
	_ = x[LargeTrap-8]
	_ = x[Lockpicks-9]
	_ = x[Manacles-10]
	_ = x[Pick-11]
	_ = x[Pole-12]
	_ = x[Pully-13]
	_ = x[Repellent-14]
	_ = x[Rope-15]
	_ = x[SpiritWard-16]
	_ = x[Spyglass-17]
	_ = x[Tinderbox-18]
	_ = x[Wolfsbane-19]
}

const _Gear_name = "Air BladderAntitoxinCartChain (10ft)Dowsing RodFire OilGrappling HookLarge SackLarge TrapLockpicksManaclesPickPole (10ft)PullyRepellentRope (25ft)Spirit WardSpyglassTinderboxWolfsbane"

var _Gear_index = [...]uint8{0, 11, 20, 24, 36, 47, 55, 69, 79, 89, 98, 106, 110, 121, 126, 135, 146, 157, 165, 174, 183}

func (i Gear) String() string {
	if i < 0 || i >= Gear(len(_Gear_index)-1) {
		return "Gear(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Gear_name[_Gear_index[i]:_Gear_index[i+1]]
}
