// Code generated by "stringer -type=Tool --linecomment"; DO NOT EDIT.

package item

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Bellows-0]
	_ = x[Bucket-1]
	_ = x[Caltrops-2]
	_ = x[Chalk-3]
	_ = x[Chisel-4]
	_ = x[CookPots-5]
	_ = x[Crowbar-6]
	_ = x[Drill-7]
	_ = x[FishingRod-8]
	_ = x[Glue-9]
	_ = x[Grease-10]
	_ = x[Hammer-11]
	_ = x[Hourglass-12]
	_ = x[MetalFile-13]
	_ = x[Nails-14]
	_ = x[Net-15]
	_ = x[Saw-16]
	_ = x[Sealant-17]
	_ = x[Shovel-18]
	_ = x[Tongs-19]
}

const _Tool_name = "BellowsBucketCaltropsChalkChiselCook PotsCrowbarDrillFishing RodGlueGreaseHammerHourglassMetal FileNailsNetSawSealantShovelTongs"

var _Tool_index = [...]uint8{0, 7, 13, 21, 26, 32, 41, 48, 53, 64, 68, 74, 80, 89, 99, 104, 107, 110, 117, 123, 128}

func (i Tool) String() string {
	if i < 0 || i >= Tool(len(_Tool_index)-1) {
		return "Tool(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Tool_name[_Tool_index[i]:_Tool_index[i+1]]
}
