// Code generated by "stringer -type=Trinket --linecomment"; DO NOT EDIT.

package item

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Bottle-0]
	_ = x[CardDeck-1]
	_ = x[DiceSet-2]
	_ = x[FacePaint-3]
	_ = x[FakeJewels-4]
	_ = x[Horn-5]
	_ = x[Incense-6]
	_ = x[Instrument-7]
	_ = x[Lens-8]
	_ = x[Marbles-9]
	_ = x[Mirror-10]
	_ = x[Perfume-11]
	_ = x[QuillAndInk-12]
	_ = x[SaltPack-13]
	_ = x[SmallBell-14]
	_ = x[Soap-15]
	_ = x[Sponge-16]
	_ = x[TarPot-17]
	_ = x[Twine-18]
	_ = x[Whistle-19]
}

const _Trinket_name = "BottleCardDeckDiceSetFace PaintFake JewelsHornIncenseInstrumentLensMarblesMirrorPerfumeQuill &  InkSalt PackSmall BellSoapSpongeTar PotTwineWhistle"

var _Trinket_index = [...]uint8{0, 6, 14, 21, 31, 42, 46, 53, 63, 67, 74, 80, 87, 99, 108, 118, 122, 128, 135, 140, 147}

func (i Trinket) String() string {
	if i < 0 || i >= Trinket(len(_Trinket_index)-1) {
		return "Trinket(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Trinket_name[_Trinket_index[i]:_Trinket_index[i+1]]
}
